# Generated by Django 5.2.3 on 2025-06-22 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_genre_alter_movie_options_remove_review_username_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='review',
            new_name='text',
        ),
    ]
